services:
  grafana:
      image: grafana/grafana:11.6.0
      container_name: grafana
      restart: unless-stopped
      environment:
        - GF_AUTH_DISABLE_LOGIN_FORM=false
        - GF_AUTH_ANONYMOUS_ENABLED=true
        - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
        - GF_AUTH_ANONYMOUS_ORG_NAME=Main Org.
        - GF_SECURITY_ADMIN_PASSWORD=admin
        - GF_SECURITY_ADMIN_USER=admin
        - GF_USERS_ALLOW_SIGN_UP=false
      volumes:
        - ./grafana/provisioning:/etc/grafana/provisioning
        - ./build:/etc/grafana/generated-dashboards
      ports:
        - "3000:3000"
